name: prasarana_rapid
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  # path: ^1.8.0
  dio: ^5.4.0
  archive: ^3.4.10
  csv: ^5.1.1
  intl: ^0.19.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
